from os import getcwd
from pathlib import Path

TARGET_FPS = 60.0

SCREEN_SIZE = (1366, 768)

PROJECT_FOLDER = Path(getcwd())

SKY_COLOR = 0x87CEEB

ASSETS_DIR = PROJECT_FOLDER / "src"

CURSORS_DIR = ASSETS_DIR / "cursors"

# cursors
CURSOR_HAND_OPEN_FILEPATH = CURSORS_DIR / "open_hand.png"
CURSOR_HAND_CLOSED_FILEPATH = CURSORS_DIR / "closed_hand.png"
CURSOR_TEXT_MARKER_FILEPATH = CURSORS_DIR / "textmarker.png"
CURSOR_NORMAL = 0
CURSOR_HAND_FINGER = 1
CURSOR_HAND_OPEN = 2
CURSOR_HAND_CLOSED = 3
CURSOR_TEXT_MARKER = 4